on:
  push:
    branches:
    - master

jobs:
  main:
    runs-on: ubuntu-latest
    name: Generate Go Documentation
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: GoDoc
        uses: ktr0731/godoc-action@v0.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Publish Updates
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: gh-pages
